id: A15D9AC0B
title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King of the
  Dralas'
type: translation
pechas:
- IEECC146B
- I5D1840E2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:00.976695
  last_modified_at: 2023-01-04 13:08:00.976699
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IEECC146B/6621: '3223'
  I5D1840E2/BE8A: '3223'
